services:
  php:
    build:
      context: .
      dockerfile: .infrastructure/docker/php/Dockerfile
      target: build-local
      args:
        - COMPOSER_TOKEN=${COMPOSER_TOKEN}
        - COMPOSER_HOME=/var/www/html/.composer
    env_file: .env
    environment:
      COMPOSER_HOME: /var/www/html/.composer
      XDEBUG_SESSION: "1"
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=MyServer"
    ports:
      - "50355:9003"
    volumes:
      - ./:/var/www/html
    command: >
      sh -c "mkdir -p .composer &&
             echo '{\"github-oauth\": {\"github.com\": \"${COMPOSER_TOKEN}\"}}' > .composer/auth.json && php-fpm"